### ISSUE TITLE
emit a multimethod for methods overloaded on type

### ISSUE THREAD

**Issue by alandipert** [alandipert/mathemagician#8]
For 1.2 buttload perf boost.  See the following example for a demonstration:

``` clojure
;;; with mathemagician's abs and a whole lotta reflection

(use 'mathemagician)
(time (dotimes [_ 1000000] (abs -2)))   ;"Elapsed time: 4419.122 msecs"

;;; with multimethod-based dispatch - faster, easy to dispatch on n args

(defmulti abs2 class)

(defmethod abs2 java.lang.Double
  [^double n]
  (java.lang.Math/abs n))

(defmethod abs2 java.lang.Long
  [^long n]
  (java.lang.Math/abs n))

(dotimes [_ 5] (time (dotimes [_ 1000000] (abs2 -2))))
;; "Elapsed time: 175.866 msecs"
;; "Elapsed time: 135.364 msecs"
;; "Elapsed time: 131.026 msecs"
;; "Elapsed time: 129.352 msecs"
;; "Elapsed time: 122.359 msecs"

;;; calling through a protocol, first-arg dispatch only. but maybe we can emit many protocols and amortize...

(defprotocol Abs
  (abs [_]))

(extend-protocol Abs
  Long
  (abs [x] (Math/abs ^long x))
  Double
  (abs [x] (Math/abs ^double x)))

(dotimes [_ 5] (time (dotimes [_ 1000000] (abs -2))))
;; "Elapsed time: 63.93 msecs"
;; "Elapsed time: 20.233 msecs"
;; "Elapsed time: 9.587 msecs"
;; "Elapsed time: 9.88 msecs"
;; "Elapsed time: 9.639 msecs"

;;; direct call for comparison

(dotimes [_ 5] (time (dotimes [_ 1000000] (Math/abs -2))))
;; "Elapsed time: 17.419 msecs"
;; "Elapsed time: 6.211 msecs"
;; "Elapsed time: 1.727 msecs"
;; "Elapsed time: 0.974 msecs"
;; "Elapsed time: 0.769 msecs"
```

**Comment by patbrown** [comment]
WTF? I'm so lost. I thought mathema' was temporary. Why do I care about dotimes tests? You are running this code at scale, but plan on moving it to more general purposes? Does java lang math transfer to other java librarires in terms of compute speed? Or am I completely lost? I thought this was an intermediate step into making it easier for programmers to incorporate standard java libraries wihtout typing so much, Or has the math gained importance? Forgive my ignorance, but I'm ignorant. Please explain... only once. WTF are we doing? I'll be able to help in no time, but I'm so confused... P.S. keeping the evolving lib here works, because the name is so dope. Yeah, I'm biased.

**Comment by alandipert** [comment]
@patbrown no worries, none of this would change the way you use the library, it would just be faster

**Comment by alandipert** [comment]
This is done and I feel pretty good about it.
